In [1]:
import numpy as np

In [3]:
new2dArray = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print new2dArray

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [4]:
# If we want to extract data at indice [1,2],[0,4],[2,3]
# extract from the array giving the row index as a list and column indexes as another list
#

subsetArray = new2dArray[[1,0,2],[2,4,3]]
subsetArray

array([ 8,  5, 14])

In [5]:
# another way if extracting is boolen way

new2dArray[new2dArray>10]

array([11, 12, 13, 14, 15])

In [6]:
# creatibg arrays using built in functions
# if you dont give, stype,by default it is floar
arrayofZeros = np.zeros((2,2),dtype='int64')
arrayofZeros


array([[0, 0],
       [0, 0]], dtype=int64)

In [8]:
arrayofOnes = np.ones((1,2))
arrayofOnes

array([[ 1.,  1.]])

In [9]:
arraywithConstantvalue = np.full(new2dArray.shape,7)
arraywithConstantvalue

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [11]:
# creating identity matrix
# pass size to eye 
identityMatrix = np.eye(2)
identityMatrix

array([[ 1.,  0.],
       [ 0.,  1.]])

In [12]:
# generates random numbers bet 0 and 1
arrayofRandomnumbers = np.random.random((2,2))
arrayofRandomnumbers

array([[ 0.41948765,  0.00541008],
       [ 0.6251481 ,  0.76798679]])

In [13]:
transposeArray = np.transpose(new2dArray)

print new2dArray.shape , transposeArray.shape


(3L, 5L) (5L, 3L)


In [14]:
# reshape 
reshapedArray =np.reshape(new2dArray,[1,15])
print reshapedArray

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [16]:
reshapedArray=np.reshape(new2dArray,[15,1])
reshapedArray

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [17]:
# mathematical operations
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[3,2,1]])


In [18]:
array1+array2

array([[ 8, 10, 12],
       [ 7,  7,  7]])

In [19]:
np.add(array1,array2)

array([[ 8, 10, 12],
       [ 7,  7,  7]])

In [20]:
np.subtract(array1,array2)

array([[-6, -6, -6],
       [ 1,  3,  5]])

In [21]:
# broadcast ----- 

array3 = [[1,4,7]]
array1+array3

array([[ 2,  6, 10],
       [ 5,  9, 13]])

In [22]:
# rule of tumb,2 array shuld have 1 dimension in common to broadcast
# Multiplication
# cols of array1 shuld be equal to rows in array2

np.dot(array1,array2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [23]:
np.dot(array1,array2.T)

array([[ 50,  10],
       [122,  28]])

In [25]:
np.multiply(array1,array2)

array([[ 7, 16, 27],
       [12, 10,  6]])

In [27]:
print(array1)
np.sum(array1)

[[1 2 3]
 [4 5 6]]


21

In [28]:
np.sum(array1,axis=0)

array([5, 7, 9])

In [29]:
np.sum(array1,axis=1)

array([ 6, 15])

In [32]:
# merging array, hstack/vstack

np.vstack((array1,array2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 2, 1]])

In [33]:
np.hstack((array1,array2))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 3, 2, 1]])

In [34]:
#Scipy for complex math functions
# spatial module ..... distance b/w 2 points
# array of diff rows, pdist --compares pair wise disatcne between all points


from scipy.spatial.distance import correlation,cosine,pdist,squareform

array1 = np.array([0,1,0])
array2 = np.array([1,0,0])

correlation(array1,array2)

1.5

In [36]:
allpoints=np.stack([array1,array2])
d=squareform(pdist(allpoints,'euclidean'))
d

array([[ 0.        ,  1.41421356],
       [ 1.41421356,  0.        ]])